import '@mdi/font/css/materialdesignicons.css'
import { VStepperVertical } from 'vuetify/labs/VStepperVertical'
// Import from Vuetify components
import { VSlideGroup } from 'vuetify/components'
import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { aliases as mdiAliases, mdi } from 'vuetify/iconsets/mdi'
import { mdSymbols } from '../utils/iconsets/mdSymbols'
import { defineNuxtPlugin } from 'nuxt/app'

export default defineNuxtPlugin(
  (app: { vueApp: { use: (plugin: unknown) => void } }) => {
    const vuetify = createVuetify({
      ssr: true,
      theme: {
        defaultTheme: 'light',
        variations: {
          colors: ['primary'],
          lighten: 0,
          darken: 1,
        },
        themes: {
          light: {
            colors: {
              primary: '#FFB300',
              secondary: '#03DAC6',
              error: '#B00020',
              info: '#2196F3',
              success: '#4CAF50',
              warning: '#FB8C00',
              grey900: '#24292F',
              grey800: '#1D2939',
              grey700: '#344054',
              grey600: '#475467',
              grey500: '#667085',
              grey400: '#98A2B3',
              grey300: '#D0D5DD',
              grey200: '#E4E7EC',
              grey100: '#f2f4f7',
              grey50: '#F9FAFB',
              grey25: '#FCFCFD',
              brandNavy: '#1E2A44',
              softGold: '#FFF8E1',
              surfaceSecondary: '#F7F8FA',
              surfaceTertiary: '#EEF1F5',
              borderSubtle: '#D8DEE8',
              borderSkeleton: '#DCDDE5',
              borderStrong: '#B8C1CF',
              shadowNeutral: '#424A53',
              errorStrong: '#C93C37',
              primary100: '#fff4bc',
              primary50: '#FFF2D1',
              lightError: '#F04438',
              greenLight700: '#02B719',
              greenLight500: '#12B76A',
              teal500: '#008080',
              greenLight25: '#F9FFF5',
              blue50: '#EFF8FF',
              blue500: '#2E90FA',
              blueGray300: '#9EA5D1',
              warning300: '#FEC84B',
              warning400: '#FDB022',
              warning500: '#F79009',
              success300: '#6CE9A6',
              success500: '#12B76A',
              generalSearchPaper: '#01C8C8',
              generalSearchPaperActive: '#BBE9BD',
              generalSearchStudyMaterialsActive: '#B3E9BA',
              generalSearchQuiz: '#7B61FF',
              generalSearchQuizActive: '#D8D0FF',
              generalSearchTutorialActive: '#C0DEFF',
              generalSearchTeacher: '#7F56D9',
              generalSearchTeacherActive: '#C7B5EE',
              generalSearchSchool: '#A15801',
              generalSearchSchoolActive: '#E3CDB3',
              generalSearchBlog: '#FF9400',
              generalSearchBlogActive: '#FFDFB3',
              white: '#FFFFFF',
            },
          },
          dark: {
            colors: {
              surface: '#FFFFFF',
              primary: '#FFB300',
              secondary: '#03DAC6',
              error: '#B00020',
              success: '#4CAF50',
              warning: '#FB8C00',
              grey900: '#24292F',
              grey800: '#1D2939',
              grey700: '#344054',
              grey600: '#475467',
              grey500: '#667085',
              grey400: '#98A2B3',
              grey300: '#D0D5DD',
              grey200: '#E4E7EC',
              grey100: '#f2f4f7',
              grey50: '#F9FAFB',
              grey25: '#FCFCFD',
              brandNavy: '#1E2A44',
              softGold: '#FFF8E1',
              surfaceSecondary: '#F7F8FA',
              surfaceTertiary: '#EEF1F5',
              borderSubtle: '#D8DEE8',
              borderSkeleton: '#DCDDE5',
              borderStrong: '#B8C1CF',
              shadowNeutral: '#424A53',
              errorStrong: '#C93C37',
              primary100: '#fff4bc',
              primary50: '#FFF2D1',
              lightError: '#F04438',
              greenLight700: '#02B719',
              greenLight500: '#12B76A',
              teal500: '#008080',
              greenLight25: '#F9FFF5',
              blue50: '#EFF8FF',
              blue500: '#2E90FA',
              blueGray300: '#9EA5D1',
              warning300: '#FEC84B',
              warning400: '#FDB022',
              warning500: '#F79009',
              success300: '#6CE9A6',
              success500: '#12B76A',
              generalSearchPaper: '#01C8C8',
              generalSearchPaperActive: '#BBE9BD',
              generalSearchStudyMaterialsActive: '#B3E9BA',
              generalSearchQuiz: '#7B61FF',
              generalSearchQuizActive: '#D8D0FF',
              generalSearchTutorialActive: '#C0DEFF',
              generalSearchTeacher: '#7F56D9',
              generalSearchTeacherActive: '#C7B5EE',
              generalSearchSchool: '#A15801',
              generalSearchSchoolActive: '#E3CDB3',
              generalSearchBlog: '#FF9400',
              generalSearchBlogActive: '#FFDFB3',
              white: '#FFFFFF',
            },
          },
        },
      },
      icons: {
        defaultSet: 'mdi',
        aliases: {
          ...mdiAliases,
        },
        sets: {
          mdi,
          md: mdSymbols,
        },
      },
      components: {
        VStepperVertical,
        VSlideGroup,
      },
    })
    app.vueApp.use(vuetify)
  },
)
