export const DEFAULT_BOARD_ID = 6627

export const PAPER_CLASSIFICATION_IDS = {
  WORKSHEET: 310,
  PREDICTED_PAPER: 8344,
  STUDY_GUIDE: 6896,
  TOPICAL_QUESTIONS: 7180,
} as const

export const MULTIMEDIA_CONTENT_TYPE_IDS = {
  VIDEO: 6022,
  PRESENTATION: 6024,
} as const
