services:
  nuxt-dev:
    container_name: nuxt-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        NODE_VERSION: "20.17.0"
    command: npm run dev
    working_dir: /app
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
