name: PR Diff Debug

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  issues: write

jobs:
  debug-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
            > files.json

      - name: Extract PR info
        id: pr_info
        run: |
          FILE_COUNT=$(jq length files.json)

          FILE_NAMES=$(jq -r '.[].filename' files.json)

          PATCHES=$(jq -r '
            .[] |
            "FILE: \(.filename)\n\n\(.patch // "No patch available")\n\n====================================\n"
          ' files.json)

          {
            echo "count=$FILE_COUNT"

            echo "files<<EOF"
            echo "$FILE_NAMES"
            echo "EOF"

            echo "patches<<EOF"
            echo "$PATCHES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Add comment to PR
        uses: actions/github-script@v7
        env:
          FILE_COUNT: ${{ steps.pr_info.outputs.count }}
          FILES: ${{ steps.pr_info.outputs.files }}
          PATCHES: ${{ steps.pr_info.outputs.patches }}
        with:
          script: |
            const pr = context.payload.pull_request

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `
                  🤖 PR Debug

                  Title:
                  ${pr.title}

                  Author:
                  ${pr.user.login}

                  Changed Files Count:
                  ${process.env.FILE_COUNT}

                  Files:
                  ${process.env.FILES}

                  ----------------------------------------

                  PATCHES

                  ${process.env.PATCHES}
                  `
            })
